### ISSUE TITLE
Feedback to external stakeholders MVP requirements

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#185]
DoD:
- [x] A spreadsheet that has been shared with the relevant stakeholders that details the scope of the Libero Editor MVP against their requirements.

**Comment by Melissa37** [comment]
https://docs.google.com/spreadsheets/d/16Lfg0M_WgH7wzYOw-lBFM0rzao3J8C7KI0GriNgFx_I/edit#gid=0
