### ISSUE TITLE
Update reference insights article to contain complete body section

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#219]
DoD:
- [x] Reference article updated with all possible elements and tags for an insights article committed to the reference-manuscripts repository.

**Comment by fred-atherden** [comment]
PR - https://github.com/libero/reference-manuscripts/pull/2

@JGilbert-eLife, @Melissa37 please take a look when you have a chance. 

(named it `pr-1` despite it being the second pr :man_facepalming:)
