### ISSUE TITLE
Get a sample XML file from Exeter

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#220]
DoD:
- [x] Get a sample XML file that contains the relevant typesetting instructions from Exeter committed as a new manuscript/article in the reference-manuscripts repository.

**Comment by Melissa37** [comment]
This will be delivered on 14th Nov
https://gitlab.com/ExeterPremedia/elife-texture/issues/4

**Comment by Melissa37** [comment]
Delivered
