### ISSUE TITLE
Build an accurate representation of a typical Insight article

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#264]
## Dod
A hosted version of a typical Insight article that we can share with the SIG for feedback.

## Tasks
- [x] To be defined by Joel

## Guidance from stakeholder
Insight articles typically include:
- a two-part title (part 1= Epigenetics: part 2= A memory of longevity)
- author details
- abstract (usually one sentence)
- body text
- figure (usually just one, sometimes none)
- references
- meta-data (article/author information) 
- a hard-wired link to one related Research Article

Occasionally there is a note or disclaimer at the end of the text. Ticket reference for notes is 'Notes #86' (Do we intend to include this for MVP). Articles with notes are:
- https://elifesciences.org/articles/50148
- https://elifesciences.org/articles/53511

Occasionally there are hard-wired links to two or more related Research Articles, as in
- https://elifesciences.org/articles/50148

Occasionally the pdf include a link to a collection, as below, but this is not needed in the release of Editor
- https://elifesciences.org/articles/53511

## Reference article(s) to recreate
- Typical Insight article https://elifesciences.org/articles/54296 (xml  https://raw.githubusercontent.com/elifesciences/elife-article-xml/master/articles/elife-54296-v1.xml)

**Comment by NuclearRedeye** [comment]
Article imported and deployed.
