### ISSUE TITLE
Author/affiliation super script numbering size to match design spec

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#279]
## Description
Super script numbering size need to match inVision design spec.

## Dod
- [ ] Superscript size for affiliations and author lists match inVision designs. Adjustment are approved by designer.

## Reference
- [inVision display prototype](https://invis.io/XBW3HLCWDT5#/406157149_article-Display)

**Comment by NuclearRedeye** [comment]
Made the relevant adjustments, and have pushed for review...
https://github.com/libero/texture/pull/24
