### ISSUE TITLE
Remove asset-level licensing copyright input

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#284]
## Description
We need to remove the copyright input on figure licensing. We have no XML requirement for this.

## Dod
- [x] Copyright input is removed from figure licensing on live Libero Editor project.

## Reference
- Asset-level licensing #79
- https://libero-editor--staging.elifesciences.org/?archive=54296#section=author-details

**Comment by NuclearRedeye** [comment]
Had a brief discussion, and it looks like just the text of the labels is incorrect and needs updating to make it clearer what the user is changing.
As such the scope of this ticket is to JUST rename the labels as per the production team's requirements. Speak to @JGilbert-eLife for the final label text.

**Comment by JGilbert-eLife** [comment]
I would suggest being straightforward and basing in on the XML tags as much as possible:

Copyright statement = `<copyright-statement>`
Copyright year = `<copyright-year>`
Copyright holder = `<copyright-holder>`
Permissions = `<license-p>`
