### ISSUE TITLE
Remove footnotes

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#285]
## Description
Remove footnotes from Libero Editor project. We do not have a requirement for this input.

## Dod
- [x] Footnotes input is removed from Libero Editor live project.

## Reference
- https://libero-editor--staging.elifesciences.org/?archive=54296#section=footnotes

**Comment by NuclearRedeye** [comment]
Had a brief discussion, and the desire is to just disable the footnotes section for now. This will be reviewed later and re-enabled and altered at a later date.
