### ISSUE TITLE
Select menu and keywords resizing

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#288]
## Description
Select menus and keywords sizing needs to match inVision design spec.

## Dod
- [x] Select menus and keyword inputs font-sizing and height are consistent with inVision designs. Adjustment are approved by designer.

## Reference
- [inVision display prototype](https://invis.io/XBW3HLCWDT5#/406157149_article-Display)
- https://libero-editor--staging.elifesciences.org/?archive=54296#section=article-information

**Comment by NuclearRedeye** [comment]
Initial work complete, but there is a discussion to be had about the how to manage the width of drop-down elements, as there are content sizing issues that may or may-not be intentional.
See..
https://github.com/libero/texture/pull/35
