### ISSUE TITLE
Journal info layout to match design spec

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#291]
## Description
Layout of journal information in article information section needs to match inVision design spec. Inputs affected are
- Article doi
- eLoc id
- Year
- Volume

## Dod
- [x] Horizontal layout of journal info inputs needs to match inVision designs. Adjustment are approved by designer.

## Reference
- [inVision display prototype](https://invis.io/XBW3HLCWDT5#/406157149_article-Display)
- https://libero-editor--staging.elifesciences.org/?archive=54296#section=article-information

**Comment by NuclearRedeye** [comment]
Tweaks to the 'jusify-content' styles.
