### ISSUE TITLE
Acknowledgements section to be displayed

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#299]
## Description
Acknowledgement section needs to be displayed to meet inVision design spec.

## Dod
- [x] Acknowledgements section is displayed on working project based on inVision design spec. Adjustments are approved by designer.

## Reference
- [inVision display prototype](https://invis.io/XBW3HLCWDT5#/406157149_article-Display)

**Comment by NuclearRedeye** [comment]
Pushed for review in...
https://github.com/libero/texture/pull/27
