### ISSUE TITLE
Sub display channels

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#323]
## Description
Features editors want the ability to be able to add a descriptive element to features content article titles so that they can attract the attention of potential readers.

## Dod
Approach to be agreed with production team

## User stories
- As a features editor, I want to add an additional descriptor to my article title so that readers can understand what topic my article relates to
- As a features editor, I want to add an additional descriptor to my article title to encourage readers to read my article
- As a features editor, I want to add an additional descriptor to my article title to increase the article’s discoverability via SEO 
- As a reader, I want to know what an article is about so that I can decide if it is of interest to me

**Comment by NuclearRedeye** [comment]
Discussed and agreed that the approach will be for the user to manually add the 'title prefix' to the title, and also to add it as a 'keyword' using the existing controls and patterns. Hence we don't think there is anything technically that needs to change at the moment.

Effort will be on the Production team to speak to Exeter with regards to changes that they might need to make to their system, e.g. to ensure that the PDF's are still generated as expected.

**Comment by Cooryd** [comment]
We now map any descriptor information to the title as a prefix via an xsl transform on import of article from Exeter. The editor app also already has the ability to edit the article title so I believe all of the requirements of this issue are now met.
