### ISSUE TITLE
Subject areas

### ISSUE THREAD

**Issue by fred-atherden** [libero/editor#36]
Categories into which content is sorted.

### Author
- [x] As an author, I want to be able to see which subject areas my manuscript has been associated with so that I check that this information is correct.

### Production staff and Erudit
- [x] As production staff, I want to be able to associate subject areas with a manuscript so that I can correct any missing information.
- [x] As production staff, I want to be able to remove subject areas associated with a manuscript so that I can adjust this information when it is incorrect.

### But what if . . . ?
- 

### Considerations
- At eLife, one or two MSAs are allowed per research-type article. Non-research content does not need to have an MSA.
- At Erudit we need to support multiple levels of categories with a maximum of 3 levels.

## XML requirements
Captured as `<subject>` elements in a `<subj-group subj-group-type="subject">` element. They are captured as children of `article-categories`. 0-2 subjects allowed in eLife articles 
```xml
<article-categories>
     <subj-group subj-group-type="subject">
          <subject>Epidemiology and Global Health</subject>
          <subject>Human Biology and Medicine</subject>
     </subj-group>
</article-categories>
```

```xml
<article-categories>
        <subj-group subj-group-type="heading">
          <subject>Articles</subject>
          <subj-group subj-group-type="heading">
            <subject>Review Articles</subject>
            <subj-group subj-group-type="heading">
              <subject>Report</subject>
            </subj-group>
          </subj-group>
        </subj-group>
        <subj-group subj-group-type="heading" xml:lang="en">
          <subject>Articles english</subject>
          <subj-group subj-group-type="heading" xml:lang="en">
            <subject>Review Articles english</subject>
            <subj-group subj-group-type="heading" xml:lang="en">
              <subject>Report english</subject>
            </subj-group>
          </subj-group>
        </subj-group>
</article-categories>
```

eLife are not wedded to the `@subj-group-type` value given.

`@xml:lang` can be used on the `subj-group` element if needed.

Subjects and keywords are currently under [JATS4R public review](https://jats4r.org/subjects-and-keywords).

Taken from: https://github.com/elifesciences/TextureRequirements/issues/22

**Comment by NickDuf** [comment]
- Available in Texture but does not meet the needs of the production team
- [See inVision](https://invis.io/DCS62CP8PZ6#/364304986_Desktop_HD) files

**Comment by fred-atherden** [comment]
See comments in #35 regarding recent edits. This ticket may be a duplicate of that one?

**Comment by NuclearRedeye** [comment]
This some internal discussion, confirmed this is a duplicate of #35 and hence I am closing this.
