### ISSUE TITLE
Display Journal Metadata

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#362]
This issue covers the implementation of support for the `<journal-meta>` element.

# User Stories

https://github.com/libero/editor/issues/16

### Additional User Stories
- [ ] As **production staff**, I want to be able to see the journal details on an article so that I can check this information is correct.

# Designs
- [Journal information prototype](https://projects.invisionapp.com/d/main#/console/19776007/414680494/preview)

# DoD
- [x] Editor updated so that the user can **see**  all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
Estimate:
0.5 dev, 0 design

**Comment by ilya-zhuravel** [comment]
@NickDuf @FAtherden-eLife this is ready for review

**Comment by fred-atherden** [comment]
👍 from me
