### ISSUE TITLE
Display and Edit Article IDs

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#363]
This issue covers the implementation of support for the `<article-id>` element.

# User Stories

https://github.com/libero/editor/issues/17

# DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 0.25
Dev: 1

**Comment by NickDuf** [comment]
@ilya-zhuravel looks good to me.

**Comment by fred-atherden** [comment]
DOI looks good thanks.

eLife also have publisher IDs:
```xml
<article-id pub-id-type="publisher-id">12345</article-id>
```

There's an accompanying user story (which I think covers both?):
> As an author, I should be able to see the article ID so that I can use it for reference in conversation with production staff.

Presume we decided not to display these, but I don't recall why.
