### ISSUE TITLE
Display and Edit Licensing and Copyright

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#365]
This issue covers the implementation of support for the `<permissions>` element, as a child of the `<article-meta>` element.

# User Stories

https://github.com/libero/editor/issues/22

### Additional User Stories
- [ ] As **production staff**, I want to be able to change the license information for an article so that I can update the license if required.

# Design
- [Licensing information prototype](https://projects.invisionapp.com/d/main#/console/19776007/419110164/preview)
- [Modal Design] (https://projects.invisionapp.com/d/main#/console/19776007/419110165/preview)

# DoD
- [ ] Contents of `<copyright-statement>`, if present, should be displayed in the 'Copyright Statement' field.
- [ ] Contents of `<license-p>` should be displayed in 'Permissions' field with support for 'ext-link'. READ ONLY
- [ ] Select with options for 'CC-BY-4.0' and 'CC0' only.
- [ ] If copyright statement is not present, should be generated from published year and first author.
- [ ] If authors are reordered, then the copyright statement should update automatically.
- [ ] If the option 'CC0' is selected, the 'Copyright Statement' field should be hidden.
- [ ] If no permissions are present, then user can choose an option from the type and all fields should be filled with default values.
- [ ] Editor updated so that the user can see and edit all the required fields.
- [ ] Solution **reviewed** and **approved** by the designer.
- [ ] Solution **reviewed** and **approved** by required stakeholders.
- [ ] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
Estimate:
Design: 0.5d
Dev: 1d

**Comment by fred-atherden** [comment]
@ilya-zhuravel  
copyright-statement - CC-By-4.0 has one and CC-0 does not.
If XML is provided with one, use what is in the XML.

In the scenario where CC0 article has been provided, and the user changes it to CC-By 4.0, Editor will have to construct the copyright statement.
It is a concatenation of the copyright symbol, the year in the publication date and copyright holder.
Here is the logic for determining the copyright holder:
- If the article has 1 author - that authors surname
- If the article has 2 authors - concatenation of: 
  - first authors surname
  - ' and '
  - second authors surname
- If the article has 3 or more authors - first author's surname + ' et al'

#### Examples
- 1 Author - © 2020, Surname
- 2 Authors - © 2020, Surname1 and Surname2
- 3+ Authors - © 2020, Surname1 et al

**Comment by fred-atherden** [comment]
Year is missing from copyright statement when generated by the Editor.

### Steps to Reproduce
- Visit [here](https://libero-editor--staging--test-cluster.elifesciences.org/?articleId=54296) and open up the Article information modal.
- Scroll down to licensing information, and note that it is currently CC-BY-4
- Change the license type to CC0.
- Change the license type back to CC-BY-4
- Note that the copyright statement is now `© , Emerson et al`, when it should be `© 2020, Emerson et al`. i.e. `2020` is missing.

**Comment by fred-atherden** [comment]
Superfluous space between 'Creative Commons Attribution License' and following comma in CC-BY-4 permissions field:
![Screenshot 2020-08-18 at 14.24.13.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/72d332b0-d234-4152-b2a0-7a00120bb6bc)

It's not there in [the XML](https://github.com/libero/editor-reference-manuscripts/blob/faa1db3aae98636b9a59a262c88e345f26d4954a/manuscripts/54296/elife-54296.xml#L133). 

[Edit: The above appears to be the _generated_ permissions statement. Follow the same steps outlined above to see this permissions statement with the extra space.]

**Comment by fred-atherden** [comment]
Superfluous space between 'Creative Commons CC0 public domain dedication' and following full stop in CC-0 permissions field:
![Screenshot 2020-08-18 at 14.26.16.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/4a07c622-54cc-45a9-8307-d4a5c4985ab6)

**Comment by fred-atherden** [comment]
I realise that the issue in my first comment above:
> Year is missing from copyright statement when generated by the Editor.

May actually be caused by a 'missing' publication date in that article. There is already is one in [the XML](https://github.com/libero/editor-reference-manuscripts/blob/faa1db3aae98636b9a59a262c88e345f26d4954a/manuscripts/54296/elife-54296.xml#L103-L106) although I think, based on [this ticket](https://github.com/libero/editor/issues/47), it's not in the element that is expected (expected is `pub-date[@publication-format="electronic" and @date-type="pub"]`  when it's actually in a `pub-date[@date-type="publication" and @publication-format="electronic"]`).

I wonder if that's the cause. 

When I add a publication date, the copyright statement displays as expected.

**Comment by fred-atherden** [comment]
I've raised a bug #522, but I think this can be fixed Post-MVP since we're not going to encounter it in our content. Looks good otherwise, thanks!
