### ISSUE TITLE
Display and Edit Article categories

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#366]
This issue covers the implementation of support for the `<subj-group subj-group-type="subject">` element.

# User Stories

https://github.com/libero/editor/issues/35

# Design

https://invis.io/A8WXRN9PQBF#/419110164_article-Info-1

# DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
Estimate:
Design: 0.25d
Dev: 1d

**Comment by FAtherden-eLife** [comment]
Pub date 
![Screenshot 2020-08-11 at 14.31.22.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/9d776ce3-2012-4ecd-a8d6-8c8f85416b1a)

comes from the following XML:
```
<pub-date publication-format="electronic" date-type="pub">
          <day>09</day>
          <month>04</month>
          <year>2019</year>
</pub-date>
```

Note that we can't always assume there will be one for Libero Editor (it may get added during proofing).

**Comment by FAtherden-eLife** [comment]
Year
![Screenshot 2020-08-11 at 14.31.22.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/5989597e-988c-4203-8446-b76202d244ca)

comes from the `<year>` element in the same XML snippet:
<pub-date publication-format="electronic" date-type="pub">
          <day>09</day>
          <month>04</month>
          <year>2019</year>
</pub-date>

**Comment by fred-atherden** [comment]
We need the ability to 'remove' subjects. Articles can have 0-2. 

[54296](https://libero-editor--staging--test-cluster.elifesciences.org/?articleId=54296) has two. I can't see any way to remove them with the current interface.

I assume the easiest option would be to allow the use to select 'Please select', which would essentially remove the subject.

**Comment by fred-atherden** [comment]
Apart from the above, it looks good.

**Comment by fred-atherden** [comment]
Sorry one more more thing...

@NickDuf, should '**Subject:** {subject}' appear once for each subject, or should both subjects be concatenated with a comma in the same line (as currently implemented)?

(In the designs, there is only one.)

If we're opting for the latter, I think the label should be changed to 'Subject(s)'

**Comment by NickDuf** [comment]
@FAtherden-eLife @ilya-zhuravel I agree with the label change to subject(s)

**Comment by fred-atherden** [comment]
Looks good, thanks.
