### ISSUE TITLE
Display and Edit Publication dates

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#375]
This issue covers the implementation of support for the `<pub-date>` element.

# User Stories

https://github.com/libero/editor/issues/47

### Additional User Stories
- [ ] As **production staff**, I want to be able to edit a publication date so that I can update it if required.

# Design
- [Important dates prototype](https://projects.invisionapp.com/d/main#/console/19776007/419110165/preview)

# DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
### Estimate
Design: 0.5d
Development: 1d

**Comment by fred-atherden** [comment]
Pub date
![Screenshot 2020-08-11 at 14.56.13.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/c5739a7f-2f23-454c-a05e-7f188a279911)
comes from the `<pub-date publication-format="electronic" date-type="pub">` element:
```
<pub-date publication-format="electronic" date-type="pub">
          <day>09</day>
          <month>04</month>
          <year>2019</year>
</pub-date>
```

[see here](https://github.com/libero/editor-reference-manuscripts/blob/faa1db3aae98636b9a59a262c88e345f26d4954a/manuscripts/54296/elife-54296.xml#L103-L107) as well.

**Comment by fred-atherden** [comment]
Year 
![Screenshot 2020-08-11 at 14.56.13.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/d2c909dc-5564-444e-bb93-dd985688938a)
comes from the `<year>` element in that same `<pub-date publication-format="electronic" date-type="pub">` element.

[Example](https://github.com/libero/editor-reference-manuscripts/blob/faa1db3aae98636b9a59a262c88e345f26d4954a/manuscripts/54296/elife-54296.xml#L106)

**Comment by fred-atherden** [comment]
Year and Published fields display 'Invalid date' if no publication date is input. Instead I think it should just say nothing, although @NickDuf can confirm the design.

![Screenshot 2020-08-12 at 09.11.42.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/abedf5cd-fcf5-45d3-a4b7-5291e989c7ad)

**Comment by fred-atherden** [comment]
Published input is really nice - I like it. Other than the above, this looks good to me.

**Comment by NickDuf** [comment]
@FAtherden-eLife @ilya-zhuravel I think it should say nothing for the time being. We can address the validation display requirements when we get to the validation strand of work.

**Comment by fred-atherden** [comment]
Looks good now, thanks
