### ISSUE TITLE
Add persistent storage to the article-store

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#406]
# DoD
- [ ] Article Store container reads and serves articles from an attached persistent store.
- [ ] Contents of store must persist over container/pod/service restarts.

**Comment by NuclearRedeye** [comment]
Spent some time looking into this yesterday with @erkannt, we discussed the various options that are available for the persistent store and there are a few options that we can look further into. We are going to discuss this further in the Office Infrastructure meeting next week, trying to come up with some tangible actions.
Options currently are:
- EBS or EKS: In both cases, the cluster needs to be updated to enable the relevant drivers. It should then be a case of creating the required resources (PersistentVolumes) and then updating the charts for Editor to include a claim and hence mount the storage into the container.
- S3: Nothing needs to be done to the cluster, but would need to work out how the bucket is created/provisioned automatically e.g. using the teraform scripts or as part of the editor chart.

There are other considerations such as backup, etc, and hence there is going to need to be some experimentation to figure out what is the best option for editors specific needs.

**Comment by erkannt** [comment]
Given the use of  Prosemirror and its json format I wonder if something like Mongo/aws DocumentDB would be a good fit.

**Comment by norisalsaadie** [comment]
Just wanted to flag some limits with MongoDB and size limit https://docs.mongodb.com/manual/reference/limits/
