### ISSUE TITLE
Pull article from bucket and upload to article-store

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#408]
# DoD
- [x] Updated importer service that can pull a file from an AWS Bucket and upload it to the article-store.
- [x] New article can be loaded, in some form (e.g. there might be some errors), in the Editor

**Comment by Cooryd** [comment]
Still todo: Hook up backend to client

**Comment by norisalsaadie** [comment]
Article xml has been loaded via the API - instructions to run this can be found here https://github.com/libero/editor-client/tree/508-load-article-from-api#getting-this-working-with-api

Note: a wider discussion is required around deployment, infrastructure etc

**Comment by norisalsaadie** [comment]
Closed as part of https://github.com/libero/editor-client/pull/128
