### ISSUE TITLE
Create an initial TOC component

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#419]
# DoD
- [x] An initial material-ui draw component as per the design.
- [x] Contains a dummy title element to start with.
- [x] When the screen size is reduced by a certain amount it should hide the drawer and add a control to the main toolbar that when clicked, makes the drawer visible again.

**Comment by NickDuf** [comment]
@NuclearRedeye @ilya-zhuravel here is my Material UI code sandbox demonstrating the drawer, appbar and main content region. https://codesandbox.io/s/libero-editor-ui-4rkui?file=/demo.js

There are two options for grid like layouts. 'Container' and 'Grid. I believe container will probably suit our needs and so have demonstrated it in the sandbox. Grid offers a lot of control although I don't believe we need this for now.

- https://material-ui.com/components/container/
- https://material-ui.com/components/grid/
