### ISSUE TITLE
Create edit reference modal

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#462]
# DoD
- [x] Create an initial modal that displays the authors list and the type fields.
- [x] Clicking the 'add reference' button should open the modal with all fields empty, and default the type to 'journal article'.
- [x] Should be able to sort the author list using the drag and drop affordance.
- [x] Should be able to delete an author using the 'delete' option from the more list.
- [x] Can change between a group author and given names/surname using the 'more' affordance.
- [x] When changing to a group author, should concat given names and surname values (if set) and use that as the value for group author.
- [x] When changing to an author from a group author, should take the value of group author (if set) and put it in the surname field.
- [x] Clicking the 'edit' button for a reference should open the modal with the relevant fields populated.
- [x] 'Done' should commit changes and close the modal.
- [x] 'Cancel' should close the modal and discard changes.
- [x] 'Delete' should show the confirm dialog.
- [x] Undo/Redo should work.

**Comment by NickDuf** [comment]
@ilya-zhuravel couple of adjustments
- When the control is activated to change an author to a group author the initials should be placed at the end of the string rather than the front. E.g. Ucar D when set to group changes to Ucar D but in a single input.
- When the new card opens it would be good to have a single empty author input as the default, with the add new button underneath.

**Comment by fred-atherden** [comment]
- Suggest changing the reference type label for preprints from 'Pre-print Article' to 'Preprint'.
- How was the current order of reference types in the select menus determined? 
![Screenshot 2020-07-31 at 13.08.07.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/45411f64-cdff-4019-a240-cb91ac2bdf95)

Periodicals are very rare so it would be better to give them less prominence in the list.
Suggest the following ordering:
- Journal Article
- Book
- Data
- Software
- Preprint
- Web Article
- Conference proceedings
- Report
- Thesis
- Patent
- Periodical

However, this is not essential for MVP, and could wait until another time.
