### ISSUE TITLE
Update the edit reference modal to support different reference types

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#463]
# DoD
- [ ] Update the modal to display all the fields for each specific reference type.
- [ ] Disable the reference type control so that a user can't change type.

**Comment by fred-atherden** [comment]
In the reference modal for a book, the '+Editor' affordance should appear between the Chapter title and the Book title instead of where it currently sits:
![Screenshot 2020-08-05 at 09.47.14.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/eb76ccad-5cf9-40da-a3a4-4cad56112314)

**Comment by fred-atherden** [comment]
In every reference type Modal (which contains Publisher location and Publisher name), Publisher location should appear before Publisher name.
For example here from a book reference:
![Screenshot 2020-08-05 at 10.08.48.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/51080952-732f-4eb5-8bbe-009d0985e837)

**Comment by fred-atherden** [comment]
Report modal - Volume and Publisher location are missing

**Comment by fred-atherden** [comment]
Data reference type - Accession URL is not needed. Either URL or DOI is fine. 

When this gets output to XML I would expect a data reference with a URL and no doi/accession number to have an `<ext-link>` and a data reference with a URL, accession and no doi, to have a `<pub-id xlink:href="{URL}">{accession number}</pub-id>` and no `<ext-link>`.

**Comment by fred-atherden** [comment]
Some fields in Data references might need label changes. For example, Specific use would mean nothing to a user, instead it should be something like 'Analyzed/Generated', but will leave that for @NickDuf to comment on.

**Comment by fred-atherden** [comment]
Specific-use field needs to be a dropdown choice, options are Generated or Analyzed.

**Comment by fred-atherden** [comment]
For references which do not have a volume and volume is an optional field, a '0' displays in the volume field in the Modal. Instead the field should be empty:
![Screenshot 2020-08-05 at 10.27.10.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/1ba15232-ac26-4d13-a49e-7097845b9ba3)

**Comment by fred-atherden** [comment]
The year field has to allow text, not a number, since we can have letters after years, such as 2020a, 2020b, 2020c etc.

**Comment by fred-atherden** [comment]
I think we should also make Volume a text field instead of mandating that it has numbers (although more often than not, it will be a number)

**Comment by fred-atherden** [comment]
PMID field not needed for the following reference types:
- Software
- Patent
- Conference Proceedings

If i missed this before, apologies.

**Comment by fred-atherden** [comment]
Report refs have two DOI and ISBN fields e.g.:
![Screenshot 2020-08-07 at 10.12.39.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/130a9d04-8f48-45c6-8f25-97b6c3aaa17b) 

Unsure if this is new or was present before, apologies if I missed it.

**Comment by fred-atherden** [comment]
Extra space between accessed date and closing square bracket `]`:

![Screenshot 2020-08-07 at 10.14.26.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/6677a232-d79f-476f-971b-bf2ee7009c08)

**Comment by fred-atherden** [comment]
Date field isn't needed for Preprints

**Comment by fred-atherden** [comment]
I think we'll need to relabel the fields, and these will need to be done on a reference type basis (i.e. what will be parsed as the same element in the XML will have a different field label in Journal/Software for example). Makes sense to wait until @NickDuf is back to set this out.
