### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#483]
### Description
1. Spacing for author bio in author information section. 12px top
2. Scroll behaviour on card showing clipping horizontally (remove horizontal scroll)
3. Inputs without value are collapsing 
4.  Links use primary color no underline (all text links should have this style, including reference list links)
5. Accessed date has square brackets [Accessed: September 10, 1995]
6.  Could we set the padding left on reference bullets from 16px to 8px (no reference image)

### Reference images
[1. author bio spacing](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/1c5d77cf-d97e-43c1-a913-c0fcce9ed920)
[2. horizontal scroll clipping](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/db58c18c-54ef-468d-8618-d732b3d11e09)
[3. Input collapse](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/482f7782-e69b-4a80-af00-96aea6318c19)
![4. link style](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/a23c28ae-7b85-4de3-add0-9aadfc5d7b06)
![5. accessed date](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/05dc749a-1589-4a42-b149-6b66d624a6bd)

**Comment by fred-atherden** [comment]
All good for production.

**Comment by NickDuf** [comment]
@ilya-zhuravel all points are clear, but point 2 requires a little more work. 

Some fixes
- Align input and buttons to match the title
- Card spacing all around should match the design values

Reference
- [design shows scroll bar placement and cards internal spacing](https://invis.io/A8WXRN9PQBF#/414680495_author-Info-2)
- [alignment ref](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/bf578dae-a8e0-460a-b5e9-139e7ff10bf7)

**Comment by ilya-zhuravel** [comment]
@NickDuf please review

**Comment by NickDuf** [comment]
@ilya-zhuravel all looks good thanks. Is it possible to adjust the scrollbar so that it isn't so close to the text fields. Similar to https://projects.invisionapp.com/share/A8WXRN9PQBF#/screens/414680495_author-Info-2 ?

**Comment by NuclearRedeye** [comment]
Raised a new issue to address the above, hence closing this issue.
