### ISSUE TITLE
Closing modal by pressing 'Done' always adds an item to the undo/redo stack

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#494]
I've noticed that when opening and closing the 'edit author' modal that an extra entry is pushed onto the undo/redo stack even when no changes have been made.

# Steps to Reproduce
1. Go to [here](https://libero-editor--staging--test-cluster.elifesciences.org/?articleId=54296)
2. Open the 'edit author' modal
3. Press 'Done' without making any changes
4. Notice how the Undo button suddenly is now enabled.

This may seem minor, but if for example made a change, then followed the steps above I would have to press undo twice to reverse the changes that I've made.

# DoD
- [ ] Only enable the 'Done' button in the modal when something has changed.

**Comment by ilya-zhuravel** [comment]
@FAtherden-eLife @NickDuf  this is ready for review

**Comment by fred-atherden** [comment]
Looks good for authors/affiliations etc. However, I'm still experiencing the same issue with the Related articles modal. That's the only one that does it as far as I can tell.
