### ISSUE TITLE
Drag and drop buttons cannot be focused

### ISSUE THREAD

**Issue by discodavey** [libero/editor#499]
Drag and drop buttons do not work with screen readers and need to be able to be focused.

## Proposed solution(s)
Read through W3C guidance on

https://www.w3.org/wiki/PF/ARIA/BestPractices/DragDrop

## Tasks
- [ ] Drag and Drop to work with screen readers

## DoD
- [ ] Drag and drop to be able to work with screen readers or have an alternate way.

**Comment by NickDuf** [comment]
@discodavey I've merged this with the author ticket.
