### ISSUE TITLE
Drag Handles hidden

### ISSUE THREAD

**Issue by discodavey** [libero/editor#500]
Drag handles have got a aria-hidden=true. This will not be read out by the screen reader so user will not know what they can do with it

## Tasks
- [ ] Remove aria-hidden so screen reader picks up drag handles

## DoD
- [ ] Drag handles to be able to be read out by screen readers

**Comment by NickDuf** [comment]
@discodavey is this on the author list or generally?

**Comment by discodavey** [comment]
Not sure why the image for the drag handle has been hidden unless Screen Reader users are not supposed to use them and they are using an alternative function to move things.

Can you let me know?

**Comment by NickDuf** [comment]
@discodavey handles are used for reordering the lists on the app. They should be accessible. Lets define a proposal.
