### ISSUE TITLE
List items to be semantically correct

### ISSUE THREAD

**Issue by discodavey** [libero/editor#512]
## Description
Article navigation is not keyboard navigable or semantically correct. 

## Tasks
- [ ] Update navigation list to match below example from MUI website.

## DoD
- [ ] List items within the article navigation area are semantically correct and keyboard navigable.

**Comment by NickDuf** [comment]
@discodavey can you let us know the accessibility issue? e.g. screen reader not understanding something...

**Comment by discodavey** [comment]
You cannot use div tags inside a UL tag unless they are inside LI's.

<img width="470" alt="Screenshot 2020-07-31 at 08 11 34" src="https://user-images.githubusercontent.com/745794/89010093-d8928680-d305-11ea-9c96-1eb9f008d79b.png">

**Comment by NickDuf** [comment]
Accessible example of drawer navigation list markup from [MUI](https://material-ui.com/components/box/) website.

`<ul class="MuiList-root MuiList-padding"><li class="MuiListItem-root jss134"><button class="MuiButtonBase-root MuiButton-root jss136 MuiButton-text" tabindex="0" type="button" style="padding-left: 24px;"><span class="MuiButton-label">Getting Started</span><span class="MuiTouchRipple-root"></span></button></li></ul>`
