### ISSUE TITLE
Reorder article sections

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#513]
## Description
Article section ordering does not follow standard article presentation.

## Solution
Article sections after the **impact statement** are presented in the following order:
1. References
2. Author information
3. Article information
4. Keywords
5. Research organism
6. Related articles

## Dod
- [ ] Libero Editors content sections ordering is approved by Libero Editor team

**Comment by fred-atherden** [comment]
@NickDuf, I think it would make sense for Article information to come directly after Author information, and before Research Organism.

Other than that it looks good to me. Thanks.
