### ISSUE TITLE
Modal styling does not match designs

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#514]
The various Modal windows in the application don't exactly match the design.

# DoD
- [x] Scrollbars in modals updated to match the [design](https://projects.invisionapp.com/share/A8WXRN9PQBF#/screens/414680495_author-Info-2).
- [x] [Title for a modal should be left aligned](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/bf578dae-a8e0-460a-b5e9-139e7ff10bf7) with the first input as per the design.
- [x] Padding for modals does not match the design.

**Comment by NickDuf** [comment]
@ilya-zhuravel 

- Title alignment is fine.
- Scrollbars/padding to match the design: If we set the section element padding-right to 20px it gives us even padding all around the card and neatens up the scroll bar spacing
- Spacing before/after inputs isn't consistent. Use author card for reference [see screen shot](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/61a94b5b-33ce-42f4-a93e-7051b5a308ea)

**Comment by ilya-zhuravel** [comment]
@NickDuf your feedback has been addressed

**Comment by NickDuf** [comment]
@ilya-zhuravel thanks! The spacing above and below the inputs looks like it still needs doing?
