### ISSUE TITLE
Formatted Reference Modal text is not highlighted

### ISSUE THREAD

**Issue by fred-atherden** [libero/editor#515]
### Steps to reproduce

Visit [here](https://libero-editor--staging--test-cluster.elifesciences.org/?articleId=00001) and open up the first reference, Berk et al.

In the 'Title' field, highlight all the text and note that _Vibrio cholerae_ is not highlighted

Add more formatting, such as bold, subscript etc. and note that those are also not highlighted:
![Screenshot 2020-08-05 at 09.41.59.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/b8026d3e-0577-4cd5-81da-1ea8bb532693)

**Comment by ilya-zhuravel** [comment]
@FAtherden-eLife ready for review
