### ISSUE TITLE
Switching between reference types loses data

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#520]
# Description
When I switch between multiple reference types, certain fields are lost when they should be preserved.

# Steps to reproduce
1. Go [here](https://libero-editor--staging--test-cluster.elifesciences.org/?articleId=54296)
2. Select the first reference, and open the edit modal.
3. Change the type to 'Data', and note the 'unsupported fields' at the bottom of the modal.
4. Change the type back to 'Journal Article', note how all the data in the 'unsupported fields' has now been lost.

# Expected Behaviour
The data should be preserved.

**Comment by NuclearRedeye** [comment]
@ilya-zhuravel This was discussed during the standup this morning and Design and Production wanted me to raise this as an issue that they'd like to be fixed for MVP.
Before you jump into it though, could you please slap an estimate on it and discuss that with the team if it's going to be a lot of work to check if they really do want it or not.

**Comment by fred-atherden** [comment]
I added comments related to this in #518. @ilya-zhuravel, let me know if you want this ticket still open or not.
