### ISSUE TITLE
Reference ordering

### ISSUE THREAD

**Issue by fred-atherden** [libero/editor#521]
As pointed out by @NickDuf, references should be ordered based on the first author's last name and year of publication.

Currently, the references remain in the order that they are provided. In order to reproduce this, add a reference and note that it always appears at the bottom of the reference list.

### Desired logic
1. Order alphabetically by surname of first author.
2. If first author surname is shared, order by year (this includes years with a, b, c etc. in them). Year is ordered chronologically, so the earlier/lower the year, the higher it comes up in the reference list. Any years with `a`s and `b`s in them should also be alphabetic (`2020a` would appear before `2020b` and so on).
3. If first author surname and year is shared, then order alphabetically by following author surnames (which could be iterated on, so order by 2nd, then 3rd etc.).

Here is an example of a reference list which uses this logic:
- Baird AH, Zarshall PA, Zarshal PA, 2001a.
- Baird AH, Marshall PA, Zarshal PA, 2001b.
- Baird AH, 2002a.
- Baird AH, 2002b.
- Baird AH, Marshall PA, 2002.
- Baird AH, Zarshall PA, 2002.
- Baird AH, Marshall PA, 2003.
- Baird AH, Marshall PA, Zarshal PA, 2004.
- Zarhall PA, 1999.

**Comment by fred-atherden** [comment]
@NuclearRedeye, the requirements are now fleshed out here and this ticket is ready to prioritise in the backlog review.

**Comment by NickDuf** [comment]
@ilya-zhuravel looks good to me

**Comment by fred-atherden** [comment]
The third condition isn't working as expected:

![Screenshot 2020-09-28 at 10.13.43.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/3499b7de-4410-4d7e-bc79-5717145d2e72)

In the above screenshot, I would expect The ref with Apple as it's second author to appear before Wad since the first author surname and year are the same.

Similarly, in this case:
![Screenshot 2020-09-28 at 10.15.01.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/7bc1044d-e15b-4658-ba0f-2930f122e5fd)

Since there is not second author, I would expect the Ather ref to appear before Ather and Wad.

**Comment by fred-atherden** [comment]
Looks good to me, thanks!
