### ISSUE TITLE
CC-BY-4 copyright statement does not update with pub date in Modal

### ISSUE THREAD

**Issue by fred-atherden** [libero/editor#522]
This is an issue that can be fixed post-MVP.

#### Steps to reproduce
- Open an article without a publication date ([example](https://libero-editor--staging--test-cluster.elifesciences.org/?articleId=00001)).
- Navigate to article information, and open up modal.
- (If there are no copyright details, then select CC-BY-4 as license type and close modal)
- Add a publication date, and note that the copyright statement will still be missing the year.

This can be fixed by clicking done, re-opening the modal, switching the license type to CC0 and then back to CC-BY-4 and clicking done.

Ideally, the copyright statement would automatically update when a pub date is added in the same modal instance.

**Comment by NickDuf** [comment]
@ilya-zhuravel the only minor snag I would add to this ticket is that the 'copyright statement' input height on the card needs to be consistent with the others.
