### ISSUE TITLE
Render all the existing reference citations

### ISSUE THREAD

**Issue by Maelplaine** [libero/editor#523]
## User stories
- [x] As an author, I want to be able to identify reference citations in the text so that I can check they are correct.

## Task
- [x] Reference citation rendered as [per design](https://projects.invisionapp.com/share/A8WXRN9PQBF#/screens/420143605)

## Dod
Staff and authors should be able to see reference citations in the main article text.

**Comment by fred-atherden** [comment]
There appears to be a superfluous space preceding some of the citations. 

![Screenshot 2020-08-24 at 11.22.17.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/f10fa17e-3581-4485-8103-463c65624bd4)

**Comment by NickDuf** [comment]
@ilya-zhuravel @FAtherden-eLife this is also fine from my perspective. I agree with Fred's above comment.

**Comment by ilya-zhuravel** [comment]
@FAtherden-eLife @NickDuf the extra space you are seeing is due to the original XML having a breakline between opening parenthesis and an xref tag and. This symbol is then rendered as a space by HTML.
