### ISSUE TITLE
insert new citation from toolbar 

### ISSUE THREAD

**Issue by Maelplaine** [libero/editor#526]
## User stories
- [x] As an Author, I want to be able to cite a reference in the text of my article so that I can indicate the relevance of a reference from my references list.

## Design
- [Menu design (1 page)](https://invis.io/A8WXRN9PQBF#/420138301_citation)

## Tasks
- [x] On click to Reference citation open the modal at cursor

# DoD
- [x]

**Comment by fred-atherden** [comment]
Looks good to me.
