### ISSUE TITLE
Display headings in main article body

### ISSUE THREAD

**Issue by Maelplaine** [libero/editor#530]
# User Stories
https://github.com/libero/editor/issues/40

# Design
- [Design headings hierarchy](https://projects.invisionapp.com/share/A8WXRN9PQBF#/screens/420013660)

# DoD
- [ ] The title text for a section should come from the `<title>` element under the `<sec>`.
- [ ] The order of heading should be read from the XML using the nesting hierarchy
- [ ] Sections should be display without indentation, e.g as a flat structure

- [ ] When the cursor is anywhere in the paragraph, selecting a heading would convert the entire paragraph

**Comment by NickDuf** [comment]
@ilya-zhuravel if you use the sandbox styles for reference on size and margin we should be good to go https://codesandbox.io/s/libero-editor-typography-qqz50?file=/demo.js

**Comment by fred-atherden** [comment]
Looks good to me - thanks.

**Comment by NickDuf** [comment]
@ilya-zhuravel this is fine thanks. We just need to set the heading line-height to 1.2.
