### ISSUE TITLE
Selecting text that includes a citation can crash the editor

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#531]
# Description

Whilst testing the new citation dialog, I found that it was possible to crash the Editor by selecting text that includes a citation. It doesn't always occur, but I've found a reliable way to reproduce it.

# Steps to Reproduce

1. Go to [here](https://libero-editor--staging--test-cluster.elifesciences.org/?articleId=54296)
2. In the main article text, position the cursor at a position just after a citation.
3. Hold the left mouse button, and move the mouse backwards to select the citation text.
4. boom

Note, that it only seems to occur when highlights text in reverse and the mouse, using the cursor keys or selecting text forwards seems to work OK.

# What should happen

I would expect that the text is highlighted, so that for example I could cut/paste it or delete it.

**Comment by fred-atherden** [comment]
Working for me.
