### ISSUE TITLE
Editing citation takes user to the top of the Main text

### ISSUE THREAD

**Issue by fred-atherden** [libero/editor#532]
### Steps to reproduce

- Visit [here](https://libero-editor--staging--test-cluster.elifesciences.org/?articleId=54296)
- Go to the last citation in the main text, Poleshko et al., 2019.
- Click and change to a separate citation.
- Note that you are scrolled to the top of the main text.

### Expected behaviour
The user should remain at the same position in the text.

**Comment by NickDuf** [comment]
@ilya-zhuravel this fix has created two new bugs.
1. After changing the citation the cite menu appears top left [screen shot](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/1d6c0dcd-4c2b-4710-a22d-dff53e228ae4)
2. citation menu doesn't stay open when activated

**Comment by fred-atherden** [comment]
Looks good now - thanks Ilya.

**Comment by NickDuf** [comment]
@ilya-zhuravel works fine for me. Thanks!
