### ISSUE TITLE
Display sections in the table of contents

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#535]
# DoD
- [ ] Correct issue with 10px of whitespace when hovering on section item in TOC.
- [ ] Table Of Contents should display sections with appropriate indentation as per the design.
- [ ] Should be able to click on the section in the TOC to navigate the main view to that section.

**Comment by NickDuf** [comment]
@ilya-zhuravel some feedback

- Remove main text as a list item
- Remove padding left from .jss5 on the ul tag
- Heading navigation doesn't currently work for me
- The button size should be the 14px text size same as the [MUI website's drawer](https://material-ui.com/components/grid/)
- 1st level like title, abstract, heading 1 to be bold, nested after to be regular

![Screenshot 2020-09-23 at 13.13.16.png](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/1a682375-c8d1-4e6f-8946-0cc80b32a46c)

**Comment by NuclearRedeye** [comment]
> Remove main text as a list item

That addition was my fault. But I did wonder do we need to add items for 'references', 'article info', etc? I figure they'd be helpful for a user to quickly jump through the document.

> Heading navigation doesn't currently work for me

Interesting, yeah it seems broken if you add a heading.

**Comment by NickDuf** [comment]
@NuclearRedeye we need links to each section like acknowledgements, references, author information, article information...

**Comment by ilya-zhuravel** [comment]
> Remove padding left from .jss5 on the ul tag

@NickDuf  the class names are often automatically generated during build so I can't use this as reference I'm afraid. Also material ui will be using that padding elsewhere so killing it for their internal class could lead to unexpected side effects. 
Could you possibly provide a screenshot which list exactly has this undesired padding?

**Comment by NickDuf** [comment]
@ilya-zhuravel no worries. 

![Screenshot 2020-09-23 at 15.23.57.png](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/a437945f-c1bb-4cec-a145-308db1b86c2f)

**Comment by ilya-zhuravel** [comment]
> @NuclearRedeye we need links to each section like acknowledgements, references, author information, article information...

@NickDuf how should we reference keywords? Each section separately by its title or just have it as Keywords?

**Comment by ilya-zhuravel** [comment]
@NickDuf your comments been address. Please test

**Comment by NickDuf** [comment]
@ilya-zhuravel this looks fine. My final adjustments are 

- Set the line-height on the list to be 1.4. This should be more readable. [See example of current line-height](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/78e533d6-c779-43f2-9c76-4b587dc09924)
- The affiliations link doesn't seem to work

**Comment by ilya-zhuravel** [comment]
@NickDuf all fixed

**Comment by NickDuf** [comment]
@ilya-zhuravel looks great! thank you. Signed off by me.
