### ISSUE TITLE
Update the editor so that it displays figures

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#545]
# DoD
- [ ] Editor can display figure image, label, title, legend and attribution inform form the article xml.

**Comment by NickDuf** [comment]
@ilya-zhuravel the general interactions work nicely for me. Just a few minor tidy up items for a closer match to the [design spec](https://invis.io/A8WXRN9PQBF#/433142658_figure-2).

- [x] The button for replace should match the design which will help with Joel's visibility suggestion on the merge request
- [x] Add a border to the picture area to match the design
- [x] Remove the card shadow and set a boarder to match input border colour
- [x] Card background colour to be white
- [x] It looks like there needs to be a little more padding between the top of the card and first input to match the design

**Comment by fred-atherden** [comment]
Nothing to add on top of what Nick has already fed back. Looks good - thanks.

**Comment by ilya-zhuravel** [comment]
@NickDuf the feedback is addressed and changes should now be in staging

**Comment by NickDuf** [comment]
@ilya-zhuravel thanks. Just need to add the picture border mentioned above.

**Comment by NuclearRedeye** [comment]
@NickDuf Should be fixed now, can you confirm when you get a chance?

**Comment by NickDuf** [comment]
@ilya-zhuravel it would probably work better to set the border on the container for the img. Just means the area is maintained along with the other inputs when empty. 

I've added some values using dev tools which should help. The border is red just for the demo but it should be the colour that you have used. 

![Screenshot 2020-10-30 at 10.41.09.png](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/c9705d7c-9b41-4a45-b760-cafa69b9f505)
