### ISSUE TITLE
Navigating through a citation using the cursor keys results in modals staying open

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#548]
# Description

As per title.

# Steps to reproduce.
1. Position cursor in a paragraph that contains multiple citations.
2. Using the arrow keys on the keyboard, move the cursor through the citations.
3. Note that the modal appears for each citation, but fails to hide once the cursor moves past the relevant citation.

# Expected behaviour.
The modal should close once the cursor has moved off the citation.

**Comment by NickDuf** [comment]
@ilya-zhuravel works for me.
