### ISSUE TITLE
Deleting a reference leaves the citations in place

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#549]
# Description

# Steps to reproduce
1. Open the editor
2. delete a reference from the references list.
3. note that any citations to the deleted reference remain intact.

# Expected Behaviour
The citations should be deleted.

# DoD
- [ ] Citations removed from the text when reference is deleted.
- [ ] Warning prompt when deleting a reference updated with new text from designer.

**Comment by ilya-zhuravel** [comment]
@NickDuf could you provide the new prompt text please?

**Comment by NickDuf** [comment]
@FAtherden-eLife does this text for the reference delete prompt seem reasonable to you?

Current text: Deleting a reference **can leave unlinked citations**. Are you sure you want to proceed?
Next text: Deleting a reference **will remove all linked citations from the article**. Are you sure you want to proceed?

**Comment by fred-atherden** [comment]
Looks good to me thanks @NickDuf

**Comment by NickDuf** [comment]
@ilya-zhuravel here is your new text for the modal... Deleting a reference will remove all linked citations from this article. Are you sure you want to proceed?

**Comment by fred-atherden** [comment]
Looks good to me

**Comment by NickDuf** [comment]
@ilya-zhuravel looks good to me.
