### ISSUE TITLE
Can't create a hyperlink in the main article body

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#552]
# Expected behaviour
Can create a hyperlink.

**Comment by NickDuf** [comment]
@ilya-zhuravel when adding a hyperlink to a single word the whole paragraph gets linked.

![Screenshot 2020-10-12 at 10.15.53.png](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/8dff9546-9f4c-4456-a5e0-1e2305f75cd6)

**Comment by fred-atherden** [comment]
This looks fixed to me. I notice that when I click a hyperlink, the text shifts to the right slightly, and then back left when the hyperlink modal is closed - unsure if that's an issue or not.

**Comment by NickDuf** [comment]
@ilya-zhuravel looks good to me. I'm not seeing the text shift Fred has reported.

**Comment by fred-atherden** [comment]
Here's what I'm seeing:
[https://app.zenhub.com/files/195217312/1d9d7d2c-d1b2-428b-abd2-f77cada47a3f/download](https://app.zenhub.com/files/195217312/1d9d7d2c-d1b2-428b-abd2-f77cada47a3f/download)
