### ISSUE TITLE
Undo of pasted heading leaves stale entry in the TOC

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#555]
# Description

# Steps to reproduce.
1. Go to [here](https://libero-editor--staging--test-cluster.elifesciences.org/?articleId=54296)
2. Scroll to the bottom of the article, add the text 'heading 2' and then using to paragraph menu to style the text as heading 2.
3. Repeat step 2, adding an additional heading. It should now look like the below.
)![Screenshot 2020-10-09 at 14.16.42.png](https://images.zenhubusercontent.com/5d556d4eb2cb743d37f7bb25/22e532b9-e237-41bf-9703-04d9e6f5f45f)
4. Select both headings, and copy and paste them so you have 4 headings.
![Screenshot 2020-10-09 at 14.16.47.png](https://images.zenhubusercontent.com/5d556d4eb2cb743d37f7bb25/2c6b1b79-5159-4248-a23b-276b67f244dd)
![Screenshot 2020-10-09 at 14.16.54.png](https://images.zenhubusercontent.com/5d556d4eb2cb743d37f7bb25/13a26fd9-7c04-4c71-8030-a01375dd6329)
5. Press undo, notice how the TOC is not incorrect.
![Screenshot 2020-10-09 at 14.17.03.png](https://images.zenhubusercontent.com/5d556d4eb2cb743d37f7bb25/6f15ba09-37e2-40c6-b0a7-e49a9e4ef49b)

# DoD
- [ ] TOC should only display the actual heading in the document.

**Comment by ilya-zhuravel** [comment]
I'm struggling to reproduce this. Could @NuclearRedeye or @FAtherden-eLife please re-test to see if it's still an issue?

**Comment by fred-atherden** [comment]
@ilya-zhuravel, I can still reproduce using the steps above:
![Screenshot 2020-10-07 at 16.40.13.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/ab7db750-409c-47d2-98d5-908c2c90c3a1)

**Comment by fred-atherden** [comment]
Looks good to me - thanks
