### ISSUE TITLE
Update the author list component to highlight the corresponding author

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#558]
# Description

The author list at the top of the article view should ideally show the corresponding author using an '*'.

# DoD
- [ ] Corresponding author highlighted in the author list using an `*`, displayed after the numbers.
- [ ] Solution deployed to the staging environment.
- [ ] Solution reviewed and approved by stakeholders.

**Comment by NickDuf** [comment]
@ilya-zhuravel this looks good to me. @FAtherden-eLife just a thought. Would it make sense to add the asterisk to the authors name further down? Some testers didn't immediately pick out the corresponding author from the list.

![Screenshot 2020-11-12 at 09.19.31.png](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/d418dc61-9884-466f-ac6a-448e31e3576b)

**Comment by fred-atherden** [comment]
> Would it make sense to add the asterisk to the authors name further down? Some testers didn't immediately pick out the corresponding author from the list.

Hmm not sure. I imagine that it would be worth user testing that again at some point, now that this functionality has been added.

This looks good to me - so going to close this ticket.
