### ISSUE TITLE
Inconsistent styling whilst trying to edit a keyword

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#559]
# Description

When trying to edit a keyword, the styling is a little inconsistent and can be confusing.

# Steps to Reproduce

1. Open the Editor
2. Navigate to the keywords component, and double click the mouse to edit any keyword. Note, that the blue background disappears.
3. Single click again to move the cursor within the edit control, and note that the blue background appears again.

# Expected Behaviour

The control should remain white, e.g. background hidden, whilst the keyword is in edit mode.

**Comment by fred-atherden** [comment]
Looks good to me - thanks
