### ISSUE TITLE
Investigate performance of postgres when storing article xml

### ISSUE THREAD

**Issue by Cooryd** [libero/editor#565]
We're investigating storage solutions for xml data taken from the kryia S3 bucket. We've briefly looked into using postgres as a solution but need to make sure that the performance will not be a blocker when storing large numbers of articles with large amounts of XML data.

As part of this we will set up a postgres DB and populate with X articles which each contain Y amount of data.

**Comment by Cooryd** [comment]
For consideration https://www.postgresql.org/docs/10/storage-toast.html

**Comment by norisalsaadie** [comment]
Some benchmarking https://github.com/libero/editor-article-store/tree/db-spike - a simple script to test how mongo and postgres cope with variable text. The script is environment driven. 

Generally speaking, for simply inserts, updates and read both mongo and postgres are good enough for what is required. The script's defaults produce a text between ~500kb - ~1mb.

**Run script:**
Use Node v12.8.0
`docker-compose up -d postgres mongo`
`node db-spike/index.js`

**Mongo:**
Mongo has a 16mb per document limit (BSON limit) that needs careful consideration. Mongo also can perform blob storage using Grid FS (https://docs.mongodb.com/manual/core/gridfs/).

In the benchmark, up to 50k documents. Mongo has performed slightly better but this may not always hold true for real world example (see example below).

The schema-less nature of Mongo might be advantages to this use case, though this introduces operational complexity (DB level schema enforcement, dropping columns etc).

**Postgres:**

Postgres is more than capable of storing and fetching large text / xml (modify the schema and insert to use xml data type).

Example output based on concurrency of 200 with 2000 documents with a content size of 542KB

***************

Mongo average write time 35.668 ms
Mongo average read time 17.659 ms
Mongo average update time 35.672 ms

Postgres average write time 60.99 ms
Postgres average read full select time 24.31 ms
Postgres average update time 60.143 ms

***************
