### ISSUE TITLE
Get assets pulled from API to display in client

### ISSUE THREAD

**Issue by Cooryd** [libero/editor#582]
Now we have endpoints for fetching assets we should call off to these from the client to display them in browser.

**Comment by norisalsaadie** [comment]
**Context:** 
The endpoint has the following shape: /articles/:articleId/assets/:assetName.ext

The xml contains relative file paths and expects the assets to be in the same directory. In addition, certain file formats are converted to jpg. 

**Question for consideration:** 

Should the client rewrite the url when it encounters an asset with the following url /exampleFile.tiff or should the backend rewrite this path when importing the data via the SQS queue?

**Comment by norisalsaadie** [comment]
Article xml and assets has been loaded via the API - instructions to run this can be found here https://github.com/libero/editor-client/tree/508-load-article-from-api#getting-this-working-with-api

Use article id of 54296

Note: a wider discussion is required around deployment, infrastructure etc

**Comment by norisalsaadie** [comment]
The approach tried so far uses img src attribute for a signed url. This approach won't work if the end point needs to be authenticated, though an XHR request with a HTTP header is an alternative to get the signed URL. Another potential consideration would be the use of cookies.

**Comment by NuclearRedeye** [comment]
> This approach won't work if the end point needs to be authenticated

Ah, so yes ultimately the endpoints will need to be authenticated. Not sure if I've discussed authentication with you at all or not, but I think we did briefly go over users and roles. Might be best to chat about it rather than pen it all down here.

**Comment by norisalsaadie** [comment]
Closed as part of https://github.com/libero/editor-client/pull/128
