### ISSUE TITLE
Create new S3 bucket, SQS queue and MongoDB through builder

### ISSUE THREAD

**Issue by Cooryd** [libero/editor#585]
After speaking to @erkannt it's apparent we should set these up through use of the builder configuration. My own understanding of how this works is limited so I will list the requirements and can give further details if needed.

- [x] We need a staging & production MongoDB (documentDB) instance for respective deployments to use.
- [x] We need a staging & production S3 bucket created for us to deposit extracted and processed article xml & assets too (unsure of what these should be named, possibly something along the lines of `${staging - prod}-elife-editor`)
- [x] We need staging & prod SQS queues set up to notify of new files being added to the bucket `elife-production-processes` which already exists. The current aim is for the staging site to be able to load in production kryia articles so both of these SQS services should point at the same `elife-production-processes` bucket.

**Comment by NuclearRedeye** [comment]
Is currently blocked on elifesciences/issues#6276
