### ISSUE TITLE
Snagging issues from first implementation

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#589]
## DoD
- [x] Fix padding on list items.
- [x] Resolve the feedback around the numbering in lists.

First implementation snagging items are here #568

**Comment by NickDuf** [comment]
@ilya-zhuravel sorry I have found two issues, but the margin and the list type switching meets spec.

Issue 1 (see first two lists captured below)
- After item 3 on unordered lists the bullet marker should return back to solid circle and then follow the same marker order based on indentation. The same type of ordering should work for numbered lists.

item 1
item 2
item 3
item 4
item 5
item 6

Issue 2 (see last list captured below)
1. Create an unordered list indenting all the way to 6 using the above text 
2. Set item 3 to a numbered list, and try to bring item 4 up onto the same line
3. A blue focus state appears on item 3 (see screen grab)

![Screenshot 2020-11-10 at 10.22.27.png](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/aee42164-f7b2-4c2e-b9d1-488699d5ebe2)
