### ISSUE TITLE
Add attribution field to Figure

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#602]
Noticed that we haven't added an attribution field to the figure. Need to add on at the end of the entries just before the license.

# DoD
- [x] Attribution field added to the editor
- [ ] Solution reviewed and approved by relevant stakeholders.
- [x] Solution deployed to production.

**Comment by fred-atherden** [comment]
Looks good to me. There's one bug it seems like, which I will raise a separate issue for, but this can be dealt with post-MVP.

**Comment by NickDuf** [comment]
@ilya-zhuravel looks good to me
