### ISSUE TITLE
Formatting of text in figure license does not work as expected.

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#605]
# Description

When trying to format text in a figure license there are some problems when using hotkeys.

# Steps to reproduce
- Visit https://libero-editor--staging--test-cluster.elifesciences.org/?articleId=54296.
- Click 'Add License'.
- Type some text in the License field.
- Highlight some/all of the text and click the hotkey for bold formatting (mac OS cmd + B). Note that the text in bolded.
- Use the hotkeys again to toggle bold (cmd + B). Note that the text remains bolded (when it should be unbolded).
- Use the hotkeys again to toggle bold (cmd + B). Note that this works, the text is now unbolded.
- Use the hotkeys again to toggle bold (cmd + B). Note that this does not work, and the text remains unbolded. 

Functionality is the same for italic, underline etc. hotkeys.

# DoD
- [ ] Issues with formatting resolved.
- [ ] Solution reviewed and approved by stakeholders

**Comment by fred-atherden** [comment]
Added steps to reproduce.

**Comment by fred-atherden** [comment]
Looks good - thanks Ilya.
