### ISSUE TITLE
Client stuck in request loop if change save fails

### ISSUE THREAD

**Issue by Cooryd** [libero/editor#609]
If a request to save a change fails then the app continues to send save requests endlessly in a loop

To reproduce:

- Bring up server and client
- load article in browser
- kill server process
- make change in client
- view network requests.

# DoD
- [x] If the user has unsaved changes and tries to leave the page, a confirmation prompt shows informing them that they have unsaved changes and are they sure they want to leave.

**Comment by NuclearRedeye** [comment]
Had a brief discussion, there are some options about how we could crudely implement at least some sort of notification to the user that they have changes that have not been saved but need to discuss with Production and Design.
