### ISSUE TITLE
Figure citation in attribution field does not work

### ISSUE THREAD

**Issue by fred-atherden** [libero/editor#618]
#### This is a post-MVP bug fix

When citing a figure in the attribution field, the figure list does not display properly. 

### Steps to reproduce
- Visit https://libero-editor--staging--test-cluster.elifesciences.org/?articleId=54296
- Navigate to the attribution field for Figure 1.
- Use the toolbar to insert a figure citation.
- Note that Figure 1 does not appear in the dropdown:
![Screenshot 2020-11-18 at 15.18.58.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/572da34d-73fd-448b-9335-35a296aaa8f1)

**Comment by ilya-zhuravel** [comment]
@FAtherden-eLife please test

**Comment by ilya-zhuravel** [comment]
@FAtherden-eLife please test

**Comment by fred-atherden** [comment]
Looks good - thanks @ilya-zhuravel
