### ISSUE TITLE
Inserting a figure no longer works

### ISSUE THREAD

**Issue by fred-atherden** [libero/editor#619]
[https://app.zenhub.com/files/195217312/9f77b4a8-4282-4dc7-8c5a-84c309a13be7/download](https://app.zenhub.com/files/195217312/9f77b4a8-4282-4dc7-8c5a-84c309a13be7/download)

**Comment by ilya-zhuravel** [comment]
@FAtherden-eLife please test

**Comment by fred-atherden** [comment]
Working now thanks @ilya-zhuravel.
