### ISSUE TITLE
In the table of contents, clicking a heading levels 2+ takes the user to the Heading 1 place in the text

### ISSUE THREAD

**Issue by fred-atherden** [libero/editor#622]
In the table of contents clicking any heading which is not Heading 1, takes the user to the Heading 1 position in the text, rather than the position of the title that they clicked. 

For example here:
![Screenshot 2020-11-24 at 14.38.36.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/9b59a642-9cc7-4225-9f1c-df64344bb887)

Clicking any of Heading 2, Heading 3, or Heading 4 scrolls the user to Heading 1 in the main text.

**Comment by ilya-zhuravel** [comment]
@FAtherden-eLife please test

**Comment by fred-atherden** [comment]
Whoah - quick fix! Looking good thanks @ilya-zhuravel.
