### ISSUE TITLE
Create an initial design that covers moving a figure in the main article body

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#624]
From recent feedback, it is desirable that the MVP supports moving a figure around in the main article body. There isn't currently a design that shows how this should look.

# DoD
- [ ] An inVision design, reviewed and approved by stakeholders.

**Comment by NickDuf** [comment]
@ilya-zhuravel here are the designs for drag and drop for assets. https://invis.io/A8WXRN9PQBF#/439485370_figure-Drag-1
@FAtherden-eLife I assume we will need the same for boxes and other article assets?

**Comment by fred-atherden** [comment]
> I assume we will need the same for boxes and other article assets?

Yup, but with regard to implementation, only figures need to be dragged for MVP. The other stuff we should save for post-MVP, since currently boxes don't have label/title fields like figures do, and we aren't yet supporting other assets. 

Design looks great, thanks @NickDuf.

**Comment by NickDuf** [comment]
@ilya-zhuravel the feature works very nicely. 

Some minor points
• On drag the entire contents of the figure is highlighted blue see grab
• Visual details blue line maker for placement to match design, and drop shadow and and blue outline until release
• Drag handles to be same colour as trash icon

![Screenshot 2020-12-09 at 14.14.49.png](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/1b02a46b-72a8-4a2e-8c66-b8368e7cf3f8)

**Comment by fred-atherden** [comment]
Thanks @ilya-zhuravel. Dragging upwards works well. 

When I drag the figure down the page the Figure number is lost.

Also If I drag the figure up, then drag it down, the editor continues to scroll down and I'm unable to stop it. Here's a video showing the behaviour:
[fig-drag.zip](https://github.com/libero/editor/files/5666612/fig-drag.zip)

**Comment by ilya-zhuravel** [comment]
@FAtherden-eLife @NickDuf feedback has been addressed

**Comment by fred-atherden** [comment]
Thanks @ilya-zhuravel, the scroll issue is resolved, but I'm still seeing this:
> When I drag the figure down the page the Figure number is lost.
