### ISSUE TITLE
Update Editor to display saving status information

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#632]
# Description

The Editor needs to let the user know when an article is saving, or when saving has failed as the backend has become unavailable.

# Design

[InVision Design File]()

# DoD
- [x] When saving, the UI presents a notification (or similar) to the user as per the design.
- [x] When saving fails, the UI present a notification (or similar) to the user as per the design.
- [x] Solution deployed to a staging environment.
- [x] Solution reviewed and approved by stakeholders.

**Comment by NickDuf** [comment]
@ilya-zhuravel all looks good. Just need the font-size to be 12px.

**Comment by ilya-zhuravel** [comment]
@NickDuf this is addressed. Please check. Thanks
