### ISSUE TITLE
Update builder to set static passwords for DocumentDB instances

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#639]
# Description

The passwords for the DocumentDB instances are not defined in the config and hence are random. When cloudformation runs, if any updates to the cluster config are done the passwords are reset to something random. We need to update builder so that the passwords are statically defined.

# DoD
- [ ] ~~Builder updated with passwords for both staging and prod environments.~~
- [ ] ~~Cloud-formation can be run, and the correct passwords are set for DocumentDB instances.~~
- [x] Update secrets for editor prod and staging environments.
- [x] Solution reviewed and approved by stakeholders.

**Comment by NuclearRedeye** [comment]
@lsh-0 I've been looking into how I could go about configuring the passwords for the documentDB instances via builder. I've done some exploration of the various code bases. I can see from the [the code in builder](https://github.com/elifesciences/builder/blob/master/src/buildercore/cfngen.py#L190) that there is already support for specifying a password which will override the generated default, but obviously this value needs to be put in a private repo and this is where my plans unravelled a bit. I assumed that those types of credentials were in `builder-private`, but having looked over the repository it appears that typically the secrets stored there are merged with the formula repos of the respective projects, e.g. the password for the database for the `profiles` service is set in `builder-private`, and the dummy value that it replaces is specified in `profiles-formula`.
Now, Editor doesn't have a formula repo for `builder`, as it's deployed as a container to the EKS cluster and hence its formula is actually a Helm chart, so based on that I'm not sure that I can actually achieve what I want as it stands without undertaking some significant work to migrate Editor so that it is completely managed via `builder`. So is there any possible alternative approach? There does seem to be looking at `builder-base-forumla` an [overall config](https://github.com/elifesciences/builder-base-formula/blob/master/pillar/elife.sls) that I might be able to shoe-horn in an entry, but I'm not certain if that's a sound approach or not.
Any help or insights you can offer would be greatly appreciated.

**Comment by lsh-0** [comment]
builder-private and the project formulas are for projects running on EC2 using Salt and not EKS. Containerisation of apps began to erode this setup and EKS ignores it entirely.

I don't know what EKS uses to manage it's secrets, we'd need to pull Daniel in to know what the best practice is regarding that.

DocDB passwords are part of the cloudformation template file and included in a payload of data this is uploaded to the server during it's initial bootstrap. You can see what is included with this data by calling `build_vars`, unfortunately you can only do that if you have a builder-managed EC2 instance.

You're going to have to pluck that password out of the template and copy it somewhere that makes EKS happy. We have Vault if it's reading from that..?

**Comment by lsh-0** [comment]
>  I can see from the the code in builder that there is already support for specifying a password which will override the generated default,

That might not be what you think it is. If it's a brand new template and no password exists, it will generate one. If it's an existing template and being updated, it will use the current password. It is passed around in cleartext a lot but the docdb instance is typically only accessible by EC2 instances covered by it's security group, and access to those EC2 instances are only available to those on a whitelist.

**Comment by NuclearRedeye** [comment]
Thanks for the response, I think I have a path forward with `build_vars` which should let me see the generated pw. I can then update the secrets in EKS to match and that should be it.

**Comment by NuclearRedeye** [comment]
Ok, `build_vars` didn't help in this instance...

```
INFO - buildercore.core - No EC2 nodes to execute on
```

Makes sense, there isn't a managed EC2 instance. However...

> That might not be what you think it is. If it's a brand new template and no password exists, it will generate one. If it's an existing template and being updated, it will use the current password.

I can just view the template through the management console and see the values I need. I'll proceed to update the secrets now, and that will resolve the issue.

**Comment by NuclearRedeye** [comment]
Secrets updated, working a charm.
