### ISSUE TITLE
Unable to delete a figure license

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#640]
# Description

I can't seem to delete a figure license, and have that change persist/

# Steps to Reproduce.

1. Go to [here](https://libero-editor--staging.elifesciences.org/?articleId=60263)
2. Scroll to the first figure, delete the license.
3. Wait a few seconds, then refresh the page.

Note how the license is back.

# Expected behaviour

The license should be deleted.

**Comment by fred-atherden** [comment]
Looking good to me.
