### ISSUE TITLE
What changes do we need to make to support properly versioning assets?

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#641]
# DoD
- [x] A collection of issues detailing the next phase of work, estimated and added to the backlog.

**Comment by ilya-zhuravel** [comment]
Here's a suggesting I have. 

1. When we call an endpoint to upload an image whether tiff or jpg/png. The server-side can keep track of just that asset, converting tiff to png and returning a unique id of the asset uploaded and a browser friendly file name. 

2. On the client side we create a new `Change` called the `FigureImageUpload` change that contains a transaction that either inserts a figure or updates figure image and the asset ID returned to the endpoint. The change will then be serialized and saved on the server. 

3. When the changes are applied to the original article to produce a new manuscript we can track which assets become obsolete and remove them from the storage.

@Cooryd @NuclearRedeye 
Let me know your thougthts. 
From the above I think we would only need two tasks, one for the server-side to create an endpoint and the other one to change client-side to support new type of change.

**Comment by NuclearRedeye** [comment]
Overall I think the approach sounds OK. Obviously I figure that typically if there are any pitfalls then they'd only become apparent by actually starting the work to implement the above. Images need to be associated with a specific manuscript, much like changes, so I assume the endpoint would be under a specific manuscript, e.g...

```
POST https://editor.elifesciences.org/api/v1/articles/123456/figures
```

How we go about cleaning up old resources is interesting, as I wonder if that has implications on how the user might want to undo a change. If I change a figure, then change my mind and hit undo i'd expect the old image to pop back in. Sounds to me like this should all work, but we just might need to be a bit clever about when we decide that an asset that isn't referenced in the article anymore is flagged as obsolete and deleted.

**Comment by Cooryd** [comment]
I like the idea as well, I take it by new manuscript you mean the versioning/ approval process in the workflow. My understanding is when this happens there no longer needs to be a granule revert process so we could purge all of the unused assets like you suggest.

**Comment by Cooryd** [comment]
#650 should add uuids to assets on the back end
