### ISSUE TITLE
Unable to save changes to the author list or affiliations

### ISSUE THREAD

**Issue by fred-atherden** [libero/editor#645]
After making an edit to the author list or affiliations, the changes are not saved.

### Steps to reproduce
- Visit https://libero-editor--staging.elifesciences.org/?articleId=60263
- Make a change to the first author (for example change their name).
- Refresh the page.
- Note that the change is not saved.

**Comment by NuclearRedeye** [comment]
@FAtherden-eLife We think this has now been fixed under the pagination work, can you retest it and confirm that it's fixed in your opinion when you get a chance? If you're happy, then feel free to close this issue.

**Comment by fred-atherden** [comment]
Yup - looks good, thanks.
