### ISSUE TITLE
What do we do when the same .zip is added to elife-production-processes?

### ISSUE THREAD

**Issue by Cooryd** [libero/editor#653]
Exeter seem to be re-creating zip files in the `elife-production-processes` bucket which are getting picked up by the importer.

Problem:
  I've noticed `elife-production-productionchecked/elife-60263-vor-r1.zip` triggered a create event on the 22nd of January & the 5th of February which means they're using the same file name to store updated values. 

How should we be handling this? Ignore the new Exeter values or try to patch what we have (this will probably not be feasible)?

# DoD
- [ ] Limit monitoring to the specified sub directories only.

**Comment by NuclearRedeye** [comment]
Discussed briefly in the backlog review, we'll for now limit to importing content only from the `elife-production-preedited` and `elife-production-copyedited` sub directories.
