### ISSUE TITLE
Single affiliation does not render correctly in the Editor

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#656]
# Description

Looking at https://libero-editor--staging.elifesciences.org/?articleId=65604, I noticed that the affiliation wasn't rendering as expected. It seems when there is only a single author and affiliation the XML is slightly different, omitting the `label` element and not putting any content in the `xref` element...

![image.png](https://images.zenhubusercontent.com/5d556d4eb2cb743d37f7bb25/c0e8987c-a02d-47a5-afd2-038ea03bb618)

# DoD
- [ ] Editor updated to support not displaying labels for an affiliation if there is only a single affiliation in the XML.
- [ ] XML when exported should also conform to the above, and not contain the `label` element or content within the `xref`?

**Comment by ilya-zhuravel** [comment]
@FAtherden-eLife it's ready for review

**Comment by fred-atherden** [comment]
Thanks @ilya-zhuravel. All working as expected.
