### ISSUE TITLE
Replacing image does not work

### ISSUE THREAD

**Issue by fred-atherden** [libero/editor#662]
When replacing a figure the image is not replaced/updated, and ![Screenshot 2021-02-18 at 14.55.31.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/4bd80611-2408-4c43-b762-42443c987db6) is rendered instead. 

Tried with tif and jpg.

https://images.zenhubusercontent.com/195217312/13e4363f-154c-4461-a8e6-f6d0544a86f8/screen_recording_2021_02_18_at_14_58_45.mov

**Comment by fred-atherden** [comment]
Images I tried using are attached 

![elife-65581-fig1.tif](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/e810524a-c213-4c00-a346-f74d558dd7cd)


![elife-66591-fig1-v1.jpg](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/46e98b7e-5533-4524-9bd1-1403f8e4fc6e)

**Comment by Cooryd** [comment]
This should now be fixed following Friday's demo.
