### ISSUE TITLE
Unable to add a keyword / adding and deleting keywords doesn't persist

### ISSUE THREAD

**Issue by Cooryd** [libero/editor#687]
I've noticed a couple of bugs around the clients keywords:

- When typing into the keyword section the input remains a `prosemirrorContainer` and never becomes a keyword-container (blue pill) like the loaded in keywords. (maybe this is intended?)
- When adding a new keyword I can only see prosemirror changes being sent in requests, should we be seeing an add-object change too? This would explain why adding new keywords doesn't persist when refreshing the page.
- I can see delete-object changes being sent as requests when removing a keyword but on refreshing the keyword still appears so it looks like this change is not being re-applied on load.

**Comment by ilya-zhuravel** [comment]
Investigation showed that we can't patch editor client to filter out conflicting changes hence we are going to need to remove them for now until merging is implemented. 

Raised a new issue #739
