### ISSUE TITLE
Clicking text after having followed a link to an external URL scrolls the user to the top of the body

### ISSUE THREAD

**Issue by fred-atherden** [libero/editor#690]
https://images.zenhubusercontent.com/195217312/a40b0776-3c5e-41ca-9698-dc3922728284/screen_recording_2021_02_25_at_10_14_59.mov

**Comment by ilya-zhuravel** [comment]
@FAtherden-eLife please test

**Comment by fred-atherden** [comment]
Looking good - thanks @ilya-zhuravel.
