### ISSUE TITLE
Move User Stories into the Libero Producer Project

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#7]
Need to move/migrate the user stories for Libero Producer to the Libero Producer project.

**DoD:**

- [ ] User Stories migrated into the Libero Producer Workspace

**Comment by fred-atherden** [comment]
@Melissa37, @JGilbert-eLife I'm unsure whether to move across the specific _types_ of reference tickets, such as [this one](https://github.com/elifesciences/TextureRequirements/issues/73), given that other potential adopters of Producer won't have the same strict requirements.

What are your thoughts here? Is it helpful for these to be pulled over?

**Comment by fred-atherden** [comment]
Further questions:
- Should we be including RRIDs - https://github.com/elifesciences/TextureRequirements/issues/95?
- Should we be including configuration - https://github.com/elifesciences/TextureRequirements/issues/87?
- Should we include file naming - https://github.com/elifesciences/TextureRequirements/issues/97?
- Should we include IDs - https://github.com/elifesciences/TextureRequirements/issues/98?
- Should we include Reference validation - https://github.com/elifesciences/TextureRequirements/issues/90?

**Comment by fred-atherden** [comment]
Note for self - list of tickets (title only) which have not been included (as of yet - some may be included):
- ~~impact statement~~
- ~~digest~~
- ~~publication history (preprint, versions)~~
- ~~sub-title~~
- ~~reviewer names~~
- ~~table source files~~
- ~~decision letter~~
- ~~author response~~
- ~~journal reference~~
- ~~book reference~~
- ~~chapter reference~~
- ~~conference reference~~
- ~~data reference~~
- ~~periodical reference~~
- ~~preprint reference~~
- ~~report reference~~
- ~~patent reference~~
- ~~software reference~~
- ~~website reference~~
- ~~thesis reference~~
- ~~configuration~~
- ~~funder validation~~
- ~~reference validation~~
- ~~rrids~~
- ~~file naming~~
- ~~ids~~

**Comment by NuclearRedeye** [comment]
Not that you asked me, but there looks like there's a lot of good information in those tickets specifically about the structure of the desired XML. My view has always been that I'd rather have information in the system twice rather than risk not putting it in at all.

**Comment by fred-atherden** [comment]
Thanks! I'll add them for now and we can discuss their usefulness at a later, more appropriate point.

**Comment by fred-atherden** [comment]
Blocked by open ticket https://github.com/elifesciences/TextureRequirements/issues/89.
