### ISSUE TITLE
Figures not displaying in some articles

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#717]
# Description

When trying to load [this article](https://libero-editor--staging.elifesciences.org/?articleId=65581), the figures don't display.

# Steps to Reproduce

1. Navigate to [here](https://libero-editor--staging.elifesciences.org/?articleId=65581)
2. Note that the figures aren't displaying

# DoD

- [ ] Can load an article in the staging environment and figures are displayed

**Comment by Cooryd** [comment]
duplicate
