### ISSUE TITLE
Images failing to load in some articles

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#738]
# Description

Whilst looking at [this](https://libero-editor--staging.elifesciences.org/?articleId=65581), I can see any images.

# What are the Steps to Reproduce to issue?

1. Go to [here](https://libero-editor--staging.elifesciences.org/?articleId=65581).

Note, the image fails to load.

# What is the Expected behaviour?

Images should load.

# Potential Solutions

I can see from the URL of the image, https://libero-editor--staging.elifesciences.org/api/v1/articles/65581/assets/ec20caa5-88ef-4fb0-8a95-fc126a07a3fa.jfif, that the extension looks incorrect.

**Comment by Cooryd** [comment]
I've tested the import of this locally and the zip is now processed correctly. Going to assume this article came in mid way through a piece of work. `.jfif` is a valid image format but our asset proxy endpoint isn't able to find the asset in S3. Will keep an eye on all new articles coming in to see if this is present anywhere else but let's resolve for now.
