### ISSUE TITLE
Generate a manifest file that contains information about the assets and when they were last updated

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#785]
# DoD
- [x] An 'endpoint', that when called returns a file which contains information about all the assets for an article and the dates that they were last changed.

**Comment by ilya-zhuravel** [comment]
```
{
  "$id": "https://example.com/person.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ArticleManifest",
  "type": "object",
  "properties": {
    "articleId": {
      "type": "string",
      "description": "unique article ID"
    },
    "type": {
      "type": "string",
      "description": "Type of the article. Defaults to insight"
    },
    "path": {
      "type": "string",
      "description": "URL of the article XML"
    },

    "assets": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "ID of a figure in the manuscript"
          },
          "type": {
            "type": "string",
            "description": "Mime type of the asset"
          },
          "path": {
            "type": "string",
            "description": "URL of the asset"
          }
        }
      }
    }
  }
}
```

**Comment by ilya-zhuravel** [comment]
@NuclearRedeye @Cooryd I posted the schema for the manifest esponse above. Let me know your thoughts.

**Comment by NuclearRedeye** [comment]
Looks like a sensible start to me. So the question will be that if i've cached either a previous copy of the manifest, or the assets, how can I determine which assets have changed or been updated from that list?

**Comment by ilya-zhuravel** [comment]
@NuclearRedeye as discussed during standup, when assets are chaning the path property will reflect such change.

**Comment by NuclearRedeye** [comment]
> @NuclearRedeye as discussed during standup, when assets are chaning the path property will reflect such change.

Yep that's fine, just wanted to make sure that is definitely the case. So just to make sure all the use cases are covered...

1. By comparing 2 manifest files, I can determine any new assets as they will only exist in the latest copy of the manifest.
2. By comparing 2 manifest files, I can determine any deleted assets as they will only exist in the old copy of the manifest.
3. By comparing 2 manifest files, I can determine if an asset has been updated by comparing the path property between the old and new manifest file.

In which case, I think that covers it.
