### ISSUE TITLE
Create an initial JSON schema for configuration for the Editor Client

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#838]
We should try to agree on a config schema before implementing.

- [ ] URLs for reaching endpoints
- [ ] toggleable TOC sections

**Comment by Cooryd** [comment]
All current API endpoints seem to be configured through function calls which return hardcoded strings here https://github.com/libero/editor-client/blob/master/src/app/api/manuscript.api.ts

**Comment by NateWr** [comment]
Yeah, and just as one maybe unexpected requirement: we need to be able to configure full URLs, not just relative paths from the domain. Our software can be run off a subdirectory like `mydomain.com/some-extra-directory-like-its-1999/`.

**Comment by Cooryd** [comment]
Thanks Nate, I'm just working on a test branch to see how might be best to get the JSON config from top level component down to this file, I'll include the absolute path requirement in my investigation.
