### ISSUE TITLE
Check we are caping image upload size to prevent DoS 

### ISSUE THREAD

**Issue by Cooryd** [libero/editor#844]
We recently ran into an issue with an article not importing due to an image pixel size limit being reached by our tif to jpeg converter. By default the `sharp` library limits an image to 268402689 total pixels (around 16k X 16k). This caused the message to endlessly live on the message queue and continuously be    re-imported. 
 
As a quick fix I've set the `sharp` option `{ limitInputPixels: false }` which doesn't check pixel size before converting. This opens us up to DoS attacks in production. 

- We should discuss a reasonable limit here to minimize this risk and check that the nginx / ingress settings are also set to limit file upload sizes.

- We need a notification system to alert us to import problems. Possibly hooking up the SQS to a SES.

**Comment by Cooryd** [comment]
10k X 10k is continuum limit

**Comment by Cooryd** [comment]
We should limit client added figs to the 16k x 16k default but there should be no limit for now on imported articles.

**Comment by NuclearRedeye** [comment]
I'm almost certain this is handled in our deployment by ingress, which limits the size of uploads via an annotation. I think the default is 1MB. You can see an example [here](https://github.com/elifesciences/elife-flux-cluster/blob/master/deployments/basex-validator/basex-validator--prod.yaml#L25) where I had to configure it to a larger number to support bigger uploads.
