### ISSUE TITLE
DTD missing from export XML

### ISSUE THREAD

**Issue by Cooryd** [libero/editor#853]
### DTD
The doctype declaration is missing from the XML file.

**Comment by Cooryd** [comment]
@FAtherden-eLife I think the missing DTD is down to the way the browser is displaying the XML. If you visit view-source:https://libero-editor--staging.elifesciences.org/api/v1/articles/70548 (no way to link so you'll need to copy that link into url bar) the `<?xml>` and `<!DOCTYPE>` tags are present. Viewing it a https://libero-editor--staging.elifesciences.org/api/v1/articles/70548 will only show you the contents of the document which is the `<article>` fragment.

```
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE article PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Archiving and Interchange DTD with MathML3 v1.2 20190208//EN"  "JATS-archivearticle1-mathml3.dtd">
<article xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ali="http://www.niso.org/schemas/ali/1.0/" article-type="article-commentary" dtd-version="1.2" specific-use="version-of-record">
...
</article>
```

**Comment by fred-atherden** [comment]
Thanks @Cooryd, yup I can see that. I take it this can be closed?

**Comment by Cooryd** [comment]
Yep, I'll close this now then. Just wanted to confirm it was outputting as expected. Thanks
