### ISSUE TITLE
License Text is sent / stored as empty on closing of article information modal

### ISSUE THREAD

**Issue by Cooryd** [libero/editor#898]
When opening the article information, the license text is always empty. On changing the license type the field then populates BUT when clicking done, and empty paragraph tag is stored as a change instead of the correct license text.

**Comment by NuclearRedeye** [comment]
A fix/workaround has now been deployed into staging. Not completely happy with the solution myself but it does seem to from the users perspective resolve the issue at hand.

**Comment by NuclearRedeye** [comment]
@Cooryd Could you add the time you spent on this to the estimate (I think you said a couple of days), and then close the issue.
