### ISSUE TITLE
Identify a suitable content type(s) to target for MVP.

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#9]
We need to identify a content type(s) that we will target to support in the MVP.

**DoD:**

- [ ] A decision on which content type(s) must be supported in the MVP

**Comment by NuclearRedeye** [comment]
@JGilbert-eLife Could you have a think about some DoD criteria for this issue?

**Comment by JGilbert-eLife** [comment]
Google sheet chart of article types and what they contain: https://docs.google.com/spreadsheets/d/1_MraWwutB1EgSUItXk0C5-Pqp7XZ2ikhhFx9AVjEl64/edit#gid=0

**Comment by JGilbert-eLife** [comment]
We have identified INSIGHTS as a suitable content type.
