### ISSUE TITLE
Chapter reference

### ISSUE THREAD

**Issue by fred-atherden** [libero/editor#99]
Reference to a specific chapter in a book.

### Author
- 
### Production staff
- 

### But what if . . . ?
- 

### Considerations
- At eLife, the minimum information for this reference type is: 
  - Authors
  - Year
  - Chapter title
  - Book title
  - Publisher
  - First page
  - Last page
- Editors, edition, publisher location and ISBN or DOI are all optional.
- We need to be able to indicate when a book reference is 'in press'. eLife does not allow any other kind of pre-publication reference, but this may vary from publisher to publisher. Other allowed statuses may include 'In preparation', 'Submitted' or 'Under review'.

## XML requirements
eLife uses the attribute `publication-type="book"`.
```xml
<element-citation publication-type="book">
      <person-group person-group-type="author">
            <name>
                  <surname>Hogarth</surname>
                  <given-names>KM</given-names>
            </name>
            <name>
                  <surname>Jaroszz</surname>
                  <given-names>J</given-names>
            </name>
            <name>
                  <surname>Butler</surname>
                  <given-names>P</given-names>
            </name>
      </person-group>
      <year iso-8601-date="2012">2012</year>
      <chapter-title>The skull and brain</chapter-title>
      <person-group person-group-type="editor">
            <name>
                  <surname>Butler</surname>
                  <given-names>P</given-names>
            </name>
            <name>
                  <surname>Mitchell</surname>
                  <given-names>A</given-names>
            </name>
            <name>
                  <surname>Healy</surname>
                  <given-names>JC</given-names>
            </name>
      </person-group>
      <source>Applied Radiological Anatomy</source>
      <edition>2nd Edition</edition>
      <publisher-loc>Cambridge</publisher-loc>
      <publisher-name>Cambridge University Press</publisher-name>
      <fpage>1</fpage>
      <lpage>32</lpage>
      <pub-id pub-id-type="doi">10.1017/CBO9780511977930.001</pub-id>
      <pub-id pub-id-type="isbn">9780511977930</pub-id>
</element-citation>
```

eLife allows the following children of `element-citation[@publication-type="book"]`:
- person-group
- year
- chapter-title
- source
- edition
- fpage
- lpage
- elocation-id
- pub-id
- publisher-name
- publisher-loc
- comment

`person-group` can contain child `name` or `collab`.

It would make sense to mandate the following elements (if specifying the difference between chapter and book references):
- person-group[@person-group-type="author"] (containing at least one `name` or `collab`)
- year
- chapter-title
- source
- publisher-name

Taken from: https://github.com/elifesciences/TextureRequirements/issues/73

**Comment by NickDuf** [comment]
No user stories at present to check this feature against

**Comment by fred-atherden** [comment]
Added `comment` to the list of allowed child elements (for 'In press' type references)
